import {SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";


export default function Home() {

  const user = useUser();

  /*
  Can bring us to the backend code from the frontend

  Two different files, run in two different places. One runs on the user's
  device. The other runs on our servers. We can go back and forth between the
  two like they are on the same machine.
  */
  const {data} = api.posts.getAll.useQuery();
  

  
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div>
          {!user.isSignedIn && <SignInButton/>}
          {!!user.isSignedIn && <SignOutButton/>}
        </div>
        <div>
          {/*Keys are a way that react uses to identify what should or shouldn't 
          be updated. Keep amount of time to render down slightly */}
          {data?.map((post) => (
            <div key={post.id}>{post.content}</div>
          ))}
        </div>
        <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
      </main>
    </>
  );
}
